---
- name: Copy ELREPO repo file
  copy:
    src: elrepo.repo
    dest: /etc/yum.repos.d/elrepo.repo

- name: Copy ELREPO repo gpg key
  copy:
    src: RPM-GPG-KEY-elrepo.org
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org

- name: "Set default kernel family"
  lineinfile:
    path: "/etc/sysconfig/kernel"
    regexp: '^DEFAULTKERNEL=kernel'
    line: "DEFAULTKERNEL=kernel-lt"

- name: Install kernel-lt packages
  yum:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      update_cache: yes
  with_items: '{{ elrepo_kernel_packages }}'
